<?php

namespace App\Models\Transaction;

use Illuminate\Database\Eloquent\Model;

class TestReportRt extends Model
{
    protected $table = "test_report_rt";

    protected $primaryKey = 'test_report_rt_id';

    public $timestamps = false;

    protected $fillable = [
        'current_location_id',
        'test_report_sequence',
        'test_report_no',
        'test_report_date',
        'customer_id',
        'material_inward_details_id',
        'nabl_type_fix',
        'job_type_fix',
        'process_type',
        'customer_client',
        'type_of_job_id',
        'job_desc_id',
        'part_id',
        'part_no',
        'drg_no',
        'material_id',
        'heat_no',
        'rt_no',
        'product_code',
        'date_of_receipt',
        'date_of_testing',
        'date_of_testing_value',
        'test_carried_out_at',
        'amendment_no',
        'amendment_date',
        'amendment_reason',
        'stage_of_test',
        'area_of_coverage_id',
        'technique_sheet_rt_id',
        'rss_reference',
        'welding_process',
        'joint_type',
        'welder_name',
        'welder_id',
        'position',
        'purpose_of_testing',
        'ir_camera_id',
        'co_camera_id',
        'xray_camera_id',
        'source_used',
        'source_strength',
        'source_size',
        'xray_kv_ma',
        'xray_focal_size',
        'lead_screen_thick',
        'lead_screen_thick_back',
        'iqi',
        'film_processing',
        'test_technique',
        'test_arrangement',
        'test_class',
        'film_brand',
        'film_type',
        'procedure_ref_id',
        'evaluation_as_per_id',
        'acceptance_standard_id',
        'customer_procedure_ref',
        'rt_report_qty',
        'film_size_unit_fix',
        'sfd_unit_fix',
        'print_ug_in_report',
        'no_of_films',
        'film_size',
        'total_area',
        'total_no_of_films_rev',
        'total_area_in_sq_rev',
        'abbreviation',
        'ulr_id',
        'ulr_no',
        'ulr_sequence',
        'ulr_year',
        'tested_by_authority_person_id',
        'reviewed_by_authority_person_id',
        'authorized_by_authority_person_id',
        'sp_note',
        'note',
        'mms_ir_192_sqin',
        'mms_co_60_sqin',
        'mms_x_ray_sqin',
        'mms_ir_192_repair_sqin',
        'mms_co_60_repair_sqin',
        'mms_x_ray_repair_sqin',
        'result',
        'observation_sheet_details_id',
        'revision_number',
        'revision_sequence',
        'revision_test_report_rt_id',
        'revision_from_report_rt_id',
        'from_type_id_fix',
        'assign_format_no',
        'company_id',
        'year_id',
        'created_by',
        'created_on',
        'last_by',
        'last_on',
        'locked_by',
        'locked_on',
    ];
}
