name: Deploy to FTP

on:
  push:
    branches:
      - ultratech-staging   # change if needed
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER_STAGING }}
          username: ${{ secrets.FTP_USERNAME_STAGING }}
          password: ${{ secrets.FTP_PASSWORD_STAGING }}
          port: 21
          server-dir: /public_html/bootstrap/
          local-dir: ./bootstrap/
          
          exclude: |
            **/.git*
            **/.github/**
            node_modules/**
            vendor/**
            .env
